[package]
name = "rust_app"
version = "0.1.0"
authors = [" Guillermo Herrera <a01400835@itesm.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
